apiVersion: v1
kind: Service
metadata:
  name: vertex-symposium
spec:
  type: NodePort
  selector:
    app: vertex-symposium
  ports:
    - name: app
      port: 4000
      targetPort: 4000
      nodePort: 30400
    - name: actuator
      port: 9090
      targetPort: 9090
      nodePort: 30090
